#!/bin/bash
function run {
  RUST_BACKTRACE=full revi $1

  if [[ $? == 127 ]];
  then
    RUST_BACKTRACE=full ./target/release/revi $1
  fi
}

function display {
  bat $1

  if [[ $? == 127 ]];
  then
    cat $1
  fi
}

cargo build --release && run $1 2> error_revi ||
  (reset && display error_revi) &&
  (reset && display error_revi)
